version: 2.1

jobs:
  build:
    machine:
      image: circleci/classic:201808-01

    steps:

      - checkout

      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
        name: Install OpenJDK 11
        command: |
            sudo rm /var/lib/apt/lists/lock
            sudo rm /var/cache/apt/archives/lock
            sudo rm /var/lib/dpkg/lock
            sudo apt install openjdk-11-jdk
            echo 'export PATH="/usr/lib/jvm/java-11-openjdk-amd64/bin:$PATH"' >> $BASH_ENV
      - run:
        name: Setup NVM
        command: |
            echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
        name: Install Node
        command: |
            nvm install
            nvm alias default
      - run:
        name: Print Java Version
        command: 'java -version'
      - run:
        name: Print Node Version
        command: 'node -v'
      - run:
        name: Print NPM Version
        command: 'npm -v'
      - run:
        name: Install Node Modules
        command: 'npm install'
      - save_cache:
        paths:
            - node
            - node_modules
            - ~/.m2
      
      - run:
        name: Give Executable Power
        command: 'chmod +x mvnw'
      - run:
        name: Run Style Checks
        command: './mvnw -ntp checkstyle:check'
      - run:
        name: Clean and Verify
        command: './mvnw -ntp clean verify'